In [445]:
import pandas as pd
import dill
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.metrics import roc_auc_score,roc_curve,scorer
from sklearn.metrics import f1_score
#working with text
from sklearn.feature_extraction.text import TfidfVectorizer
#normalizing data
from sklearn.preprocessing import StandardScaler
#pipeline
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.metrics import precision_score,recall_score
#imputer
from sklearn.impute import SimpleImputer

import sklearn.datasets

In [603]:
df = pd.read_csv(r'C:\Users\Матвей\Salary_Data.csv')
df.head(3)

   YearsExperience   Age  Salary
0              1.1  21.0   39343
1              1.3  21.5   46205
2              1.5  21.7   37731

In [604]:
df.shape

(30, 3)

In [605]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  30 non-null     float64
 1   Age              30 non-null     float64
 2   Salary           30 non-null     int64
dtypes: float64(2), int64(1)
memory usage: 848.0 bytes

In [606]:
from sklearn.model_selection import train_test_split

features = ['YearsExperience', 'Age']
target = 'Salary'

X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            shuffle=True,
            test_size=0.3,
            random_state=42
        )

In [607]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

    
class OHEEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, key):
        self.key = key
        self.columns = []

    def fit(self, X, y=None):
        self.columns = [col for col in pd.get_dummies(X, prefix=self.key).columns]
        return self

    def transform(self, X):
        X = pd.get_dummies(X, prefix=self.key)
        test_columns = [col for col in X.columns]
        for col_ in test_columns:
            if col_ not in self.columns:
                X[col_] = 0
        return X[self.columns]

YearsExperience = Pipeline([
                ('ohe', OHEEncoder(key='YearsExperience'))
            ])

In [608]:
gender.fit_transform(X_train, y_train)

,YearsExperience_1.1,YearsExperience_1.3,YearsExperience_1.5,YearsExperience_2.0,YearsExperience_2.2,YearsExperience_2.9,YearsExperience_3.0,YearsExperience_3.2,YearsExperience_3.9,YearsExperience_4.0,...,YearsExperience_4.5,YearsExperience_5.1,YearsExperience_5.9,YearsExperience_6.0,YearsExperience_6.8,YearsExperience_7.1,YearsExperience_7.9,YearsExperience_9.0,YearsExperience_9.5,YearsExperience_10.5
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
7,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
6,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [609]:
from sklearn.preprocessing import StandardScaler

tenure =  Pipeline([
                ('selector', NumberSelector(key='tenure')),
                ('standard', StandardScaler())
            ])

In [610]:
from sklearn.preprocessing import StandardScaler
YearsExperience =  Pipeline([
                ('selector', NumberSelector(key='YearsExperience')),
                ('standard', StandardScaler())
            ])

In [611]:
from sklearn.preprocessing import StandardScaler

Age =  Pipeline([
                ('selector', NumberSelector(key='Age')),
                ('standard', StandardScaler())
            ])

In [612]:
feats = FeatureUnion([('Age', Age)])
feature_processing = Pipeline([('feats', feats)])

In [613]:
from sklearn.ensemble import RandomForestClassifier

pipeline = Pipeline([
    ('features',feats),
    ('classifier', RandomForestClassifier(random_state = 42)),
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('features',
                 FeatureUnion(transformer_list=[('Age',
                                                 Pipeline(steps=[('selector',
                                                                  NumberSelector(key='Age')),
                                                                 ('standard',
                                                                  StandardScaler())]))])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [614]:
y_pred = pipeline.predict_proba(X_test)
y_pred

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.01      , 0.03      , 0.07      , 0.62      ,
        0.27      ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.18483333, 0.        , 0.13516667, 0.        ,
        0.68      , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.18016667,
        0.        , 0.14983333, 0.63      , 0.04      , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.005     , 0.        , 0.005     , 0.        ,
        0.08      , 0.        , 0.66      , 0.22      , 0.        ,
        0.03      , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.6       , 0.005     , 0.1425    , 0.005     , 0.1975    ,
        0.        , 0.05      , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.18      , 0.05216667, 0.        , 0.06783333, 0.        ,
        0.        , 0.7       , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.01      , 0.03      , 0.07      , 0.28      ,
        0.61      ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.01333333,
        0.        , 0.02666667, 0.06      , 0.64      , 0.26      ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.02      , 0.4345    , 0.        , 0.4955    , 0.        ,
        0.        , 0.05      , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [620]:
roc_auc_score(y_test.values.ravel(), y_pred[:,0])

ValueError: multi_class must be in ('ovo', 'ovr')